# Generated by Django 4.0.3 on 2022-03-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_categories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Old', 'Old')], max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft')], max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='stoke',
            field=models.CharField(choices=[('IN STOCK', 'IN STOCK'), ('OUT OF STOCK', 'OUT OF STOCK')], max_length=300),
        ),
    ]
